### ISSUE TITLE
Steps #7,8,9 returns error

### ISSUE THREAD

**Issue by ngov** [dwyl/web-form-to-google-sheet#11]
The form sends emails fine, but the _html contact form sendEmail_ Run doesn't contain doGet and on running the latest code test in step 8, low and behold there's an error: "Script function not found: doGet"

**Comment by nelsonic** [comment]
@ngov I removed `doGet`. 
please see: https://github.com/dwyl/html-form-send-email-via-google-script-without-server for the latest version of this script.

**Comment by ngov** [comment]
Tried this once again exactly as written, and it works perfectly in personal Google Sheets! Does not work in Business Google though... where I started originally.

Don't suppose it could be made to...?

**Comment by nelsonic** [comment]
@ngov hmm... good question. I did originally test it with Google Apps for a Business. What are you seeing? it might be that the Admin for your Google Apps account has disabled API access... are you able to check?

**Comment by ngov** [comment]
Contacted our admin, this did the trick! 
Thanks :+1:

**Comment by nelsonic** [comment]
Thought that might be the reason. 
Glad you got it working.
Once you're happy please close this GitHub issue. :+1:
