### ISSUE TITLE
How can I add my own success message when and email is sent?

### ISSUE THREAD

**Issue by j-salce** [dwyl/web-form-to-google-sheet#20]
Hello!

I'll do my best to explain this, but I have this site currently http://107.170.219.136/ 

When you submit the contact form it updates the page and displays a Thank You message. How can I achieve this while also sending the information to google sheets? I have the google sheets working but when I submit it takes me to a separate page that displays a JSON success message like the following:
 
`{"result":"success","row":6}`

How can I keep the same functionality that I have on the current dev site? Where do I add it? Thanks!

**Comment by mckennapsean** [comment]
This repo covers some of the same steps, but it includes an example form which hides the form and un-hides or displays a div to show a thank you message, similar to what you described. The code you have is also displaying a div upon an error, so you could also just customize the success to add its own div (and hide the form) if you want to as well.

**Comment by j-salce** [comment]
Hey @mckennapsean thanks for sharing. This worked great! My only problem right now is that if you submit the form it will sometimes display the Thank You messages within a DIV as it's supposed too, but there are some occasions where the JSON success page pops up instead of the Thank you DIV. Any thoughts on this?

**Comment by mckennapsean** [comment]
That sounds like a potential browser-specific issue that may have cropped up on the other repository too. If you haven't yet, I would check out its Javascript to see if anything is updated there. Not sure aside from that though.

**Comment by j-salce** [comment]
Thanks @mckennapsean !

**Comment by j-salce** [comment]
Seems like the solution stopped working? Not sure, but everytime I submit the form it now just gives me the JSON message :/

**Comment by mckennapsean** [comment]
Not sure what you mean. You created another issue, #21. Is this related at all? It was useful to have a page to look at that you listed above, but it sounds like you were able to solve this particular issue but hit another snag.
